# Generated by Django 5.2.7 on 2025-10-03 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время совершения платежа', verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Размер платежа в валюте', max_digits=10, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank_transfer', 'Перевод на счет')], help_text='Метод оплаты (наличные, перевод и т.д.)', max_length=20, verbose_name='Способ оплаты')),
                ('course', models.ForeignKey(blank=True, help_text='Курс, за который произведена оплата', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(blank=True, help_text='Урок, за который произведена оплата', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(help_text='Пользователь, совершивший платеж', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
    ]
